### ISSUE TITLE
Funding for note-taking for core devs call #63

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/funding#11] opened 2019-06-26 17:00 UTC
note-taking for core devs [call #63](https://github.com/ethereum/pm/pull/106)

**Comment by DBrettRobertson** [comment] 2019-08-13 14:45
@mjplacroix please provide an address for payment.

**Comment by mjplacroix** [comment] 2019-08-17 14:24
DAI: 0xa877846f4f4d115B2e2e55249BDdFABCF5CB2f80
USDC: 0xee2586c5145dFebe65E8b32737a34FD44201cc55

LMK if you need a different address.

**Comment by Souptacular** [comment] 2019-08-29 19:25
Multisig TX: https://etherscan.io/tx/0x719ab361b113f46087e56965d1c551b3f57d1167d75b4899f41a8cda128f8186

@CPSTL should be confirming it soon.

**Comment by lrettig** [comment] 2019-09-20 20:08
Looks like @CPSTL cross-confirmed the first of these here: https://etherscan.io/tx/0x2b597a6f8417e32f48c9969ee39d90cab51568ac07470397859063dbb99c245b; I just confirmed the second here: https://etherscan.io/tx/0x2dde0f1ee4a87b3ed0c7c918f8ee7773d353e248600c14eca25897c08ce0f087. Spreadsheet updated! Closing

https://docs.google.com/spreadsheets/u/1/d/1PMCKHrkD2oGNXnDi6chy9DOFbpXgDRqpNz75PXSzoj4/edit#gid=0

**Closed by lrettig** 2019-09-20 20:08 UTC
Labels: Meeting Notes
