### ISSUE TITLE
Funding for note-taking for core devs call #64

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/funding#13] opened 2019-07-10 20:19 UTC
note-taking for core devs [call #64](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2064.md)

**Comment by DBrettRobertson** [comment] 2019-08-13 14:52
Funds related to Core Dev Call 64 notes can be sent to: DBrettRobertson.gitcoin.eth

**Comment by Souptacular** [comment] 2019-08-29 19:26
Multisig TX: https://etherscan.io/tx/0x1f56a17eed14a2b77e24a90dd47e989a16886900dfd1b4d3a447f2eaeac02f03

@CPSTL should be confirming it soon.

**Comment by lrettig** [comment] 2019-09-20 20:13
Looks like @CPSTL confirmed the first of these (https://etherscan.io/tx/0x034e85815c5c65befa6c32e49172553e2510d1a1ebc29f87164b29a273dd9c02); I just confirmed the second (https://etherscan.io/tx/0xfe3a7151035880e80a6c276d571ff8abfd61ca5175855b72243c4eb911aa3e6e) and updated the spreadsheet (https://docs.google.com/spreadsheets/d/1PMCKHrkD2oGNXnDi6chy9DOFbpXgDRqpNz75PXSzoj4/edit#gid=0). Closing.

**Closed by lrettig** 2019-09-20 20:13 UTC
Labels: Meeting Notes
